project:
  type: website
  output-dir: docs

website:
  favicon: favicon.ico
  title: "Brain Busters - Javascript Games"
  reader-mode: false
  open-graph: true
  page-navigation: true
  page-footer: "Copyright 2025, Muthukrishnan" 
  google-analytics: 
    tracking-id: 'G-BH3P7R68Z6'
  site-url: 'https://games.muthu.co'
  site-path: '/'
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/muthuspark/javascript-games
      - icon: twitter
        href: https://twitter.com/krimuthu
format:
  html:
    theme: litera
    css: styles.css
    lang: en
    toc: true
    image: false
    include-before-body:
    - text: |
        <link rel="stylesheet" href="/posts/global.css"></link>
        <script type="text/javascript" src="/posts/global.js"></script>
    include-after-body:
    - text: |
        <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-3609399560636561" crossorigin="anonymous"></script>


